feat: configure command set env variables
superfaceai/cli pull request #108
Opened 2021-08-02 14:32 UTC by Jakub-Vacek

## Description

This PR enables configure command to add expected names of environment variables to .env file.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation accordingly. For updating Oclif commands documentation use [oclif-dev](https://github.com/oclif/dev-cli#oclif-dev-readme).
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-08-03 09:26 UTC, martinalbert requested changes

2021-08-03 09:26 UTC, martinalbert commented on src/logic/configure.ts
> +  }
Wouldn't be better to use `readFileQuiet` which returns `string | undefined`?

```suggestion
  let envContent: string | undefined;
  //Get .env file
  if (await exists('.env')) {
    envContent = await readFileQuiet('.env');
  }
```

2021-08-03 09:26 UTC, martinalbert commented on src/logic/configure.test.ts
> +        `TEST_API_KEY=something\nTEST_TOKEN=\nTEST_PASSWORD=\nTEST_DIGEST=\n`
`TEST_USERNAME` is missing

2021-08-03 09:26 UTC, martinalbert commented on src/logic/configure.ts
> +    }
You're reassigning templated string under `isBasicAuthSecurityScheme(scheme)` condition. Maybe new function that would encapsulate these if statements in env template module would be cool.

```suggestion
  for (const scheme of securitySchemes) {
    const value = composeEnvVariables(scheme, envProviderName)
    
    if (value === undefined) {
      options?.warnCb?.(
        `⚠️  Provider: "${provider}" contains unknown security scheme`
      );
    }
```

2021-08-04 08:57 UTC, lukas-valenta approved these changes

2021-08-04 09:45 UTC, merged