[WIP]feat: test template from profile examples
superfaceai/cli pull request #234
Opened 2022-11-02 11:30 UTC by Jakub-Vacek

## Description

This PR add ability to prepare test file for specific profile and provider. Code needs to be changed to use same example structure as in https://github.com/superfaceai/cli/pull/231. 

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly. For updating Oclif commands documentation use [oclif-dev](https://github.com/oclif/dev-cli#oclif-dev-readme).
- [ ] I have read the **CONTRIBUTION_GUIDE** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-29 13:06 UTC, tmladek requested changes
```
    it('should map error', async () => {
      const result = await superface.run({
        useCase: 'FaceDetection',
        input: {
          code : '14',
          message : 'We can not access the URL currently. Please download the content and pass it in.',
        }
      })
```
      
I don't think this is correct; `input` [should correspond to](https://github.com/superfaceai/station/blob/main/grid/computer-vision/face-detection/profile.supr#L166) `imageUrl = 'https://upload.wikimedia.org',`

2022-11-29 14:05 UTC, martinalbert commented
I would also consider specifying test instance in constructor since it's already generated for jest.

2022-11-29 15:02 UTC, tmladek requested changes

2022-11-29 15:02 UTC, tmladek commented on src/templates/prepared-test/test-templates/error.ts
> +    expect(() => result.unwrap()).not.toThrow();
```suggestion
    expect(() => result.unwrap()).toThrow();
```

2022-12-06 11:28 UTC, kysely approved these changes
I like this, thanks 🙏 

A question though: I see it's becoming a pattern [in Station to define provider-agnostic test](https://github.com/superfaceai/station/blob/main/grid/language/analyze-plain-text-sentiment/maps/analyze-plain-text-sentiment.ts) which is then ran against all providers.

Is this the way we'd like to go forward with in the future? @tmladek

2022-12-06 11:48 UTC, merged